/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CircularDependencyPlugin = require("circular-dependency-plugin");

module.exports = require("./webpack.base.babel")({
  mode: "development",

  // Add hot reloading in development
  entry: [
    require.resolve("react-app-polyfill/ie11"),
    "webpack-hot-middleware/client?reload=true",
    path.join(process.cwd(), "app/app.js"), // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },

  optimization: {
    splitChunks: {
      chunks: "all",
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new webpack.EnvironmentPlugin({
      SERVER_URL: "http://localhost:7000/api",
      RAZORPAY_KEY: "rzp_test_RLM7fjm2Fi8KdM",
      WHATSAPP_TOKEN: "EAALnfn2bArEBADQOsp2BE6yvhQssexZCR0qk9SARu7tEu0LAkjl6qRGW7nZBWIfmdDsS3iOEGTf1OBE4xIcskkZB4XCmg6W3X7K8d6eyrkpMs5sYZB3VaQeEbOTKXKLUXNdYD9AZAAEpVifcW9yZAgSIZCwdBbFZC3TP2vyQYEm8DH7EmJEpg4OYNM42yMg7ECM823cOuErIIgZDZD",
    }),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "app/index.html",
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",

  performance: {
    hints: false,
  },
});
